[project]
name = "blockchain-loyalty-rewards-network"
description = "Blockchain project: blockchain-loyalty-rewards-network"
authors = ["Automated Builder <automation@blockchain.dev>"]
telemetry = false
cache_dir = ".clarinet"
requirements = []

[contracts.merchant-rewards-gateway]
path = "contracts/merchant-rewards-gateway.clar"
depends_on = []

[contracts.universal-points-ledger]
path = "contracts/universal-points-ledger.clar"
depends_on = []

